services:
  mysql:
    image: mysql:8.0
    container_name: nest_guigu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: nest_guigu
    ports:
      - '3307:3306'
    volumes:
      - nest_guigu_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-proot123456',
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  nest_guigu_data:
